// <auto-generated />
using System;
using CollectorCommands.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectorCommands.Migrations
{
    [DbContext(typeof(CommandsDbContext))]
    [Migration("20260316211234_AddsEntitiesRelationship")]
    partial class AddsEntitiesRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectorCommands.Models.ArticleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasJsonPropertyName("name");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasJsonPropertyName("price");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasJsonPropertyName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.ToTable("Articles");

                    b.HasAnnotation("Relational:JsonPropertyName", "articles");
                });

            modelBuilder.Entity("CollectorCommands.Models.CommandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("buyerId");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("sellerId");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasJsonPropertyName("state");

                    b.Property<double>("Total")
                        .HasColumnType("float")
                        .HasJsonPropertyName("total");

                    b.Property<double>("TotalHt")
                        .HasColumnType("float")
                        .HasJsonPropertyName("totalHt");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("CollectorCommands.Models.ArticleModel", b =>
                {
                    b.HasOne("CollectorCommands.Models.CommandModel", "Command")
                        .WithMany("Articles")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("CollectorCommands.Models.CommandModel", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
