name: Trigger auto deployment for commands

on:
  push:
    branches: 
      [ master ]
    tags:
      - 'v*'
    paths:
    - '**'
    - '.github/workflows/commands-AutoDeployTrigger-243b90ac-a1fd-48c7-a811-ad7de68e98ca.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  sonarqube:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17 # Nécessaire pour sonarqube
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
          
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner
          
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"MaximeBro_Collector" /o:"maximebro" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  
  build:
    needs: sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v4

      - name: 2 - SDK .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: 3 - Restore des packages
        run: dotnet restore

      - name: 4 - Build
        run: dotnet build --no-restore --configuration Release

      # - name: 5 - Tests unitaires
      #   run: dotnet test CollectorCommands.Tests/CollectorCommands.Tests.csproj --no-build --configuration Release --verbosity normal

      # - name: 6 - Tests d'intégration
      #   run: dotnet test CollectorCommands.IntegrationTests/CollectorCommands.IntegrationTests.csproj --no-build --configuration Release --verbosity normal
        
  unit-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v4

      - name: 2 - SDK .NET 10
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '10.0.x'

      - name: 3 - Tests unitaires
        run: dotnet test CollectorCommands.Tests/CollectorCommands.Tests.csproj --configuration Release --verbosity normal

  integration-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 1 - Checkout
        uses: actions/checkout@v4

      - name: 2 - SDK .NET 10
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '10.0.x'

      - name: 5 - Tests d'intégration
        run: dotnet test CollectorCommands.IntegrationTests/CollectorCommands.IntegrationTests.csproj --configuration Release --verbosity normal

  deploy:
    needs: [build, unit-test, integration-test]
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.COMMANDS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COMMANDS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COMMANDS_AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          echo ${{ secrets.COMMANDS_REGISTRY_PASSWORD }} | docker login collectorcr.azurecr.io -u ${{ secrets.COMMANDS_REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t collectorcr.azurecr.io/commands:${{ github.sha }} -f ./CollectorCommands/Dockerfile .
          docker push collectorcr.azurecr.io/commands:${{ github.sha }}

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: collectorcr.azurecr.io/commands:${{ github.sha }}
          containerAppName: commands
          resourceGroup: collector
